NaCosAppFig:
  NamespaceId: "544c7bc6-d899-40cc-81ec-ab7733bdbc6f"
  IpAddr: "14.103.149.192"
  Port: 8848
  DataId: 2209a
  Group: dev

MqttFig:
  Broker: mqtt://14.103.140.6:1883
  Topic: client
  Qos: 1
  UserName: test
  Password: 1gzrhhsc5YDHR