// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: order.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// todo 商品下单进队列
type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=ProductId,proto3" json:"ProductId,omitempty"`
	Num           int64                  `protobuf:"varint,3,opt,name=Num,proto3" json:"Num,omitempty"`
	Pay           int64                  `protobuf:"varint,4,opt,name=Pay,proto3" json:"Pay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateOrderRequest) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *CreateOrderRequest) GetPay() int64 {
	if x != nil {
		return x.Pay
	}
	return 0
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       string                 `protobuf:"bytes,1,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=Url,proto3" json:"Url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderResponse) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *CreateOrderResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// todo: 消费队列创建订单
type CreateOrderMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderMessageRequest) Reset() {
	*x = CreateOrderMessageRequest{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderMessageRequest) ProtoMessage() {}

func (x *CreateOrderMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderMessageRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderMessageRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

type CreateOrderMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ping          string                 `protobuf:"bytes,1,opt,name=Ping,proto3" json:"Ping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderMessageResponse) Reset() {
	*x = CreateOrderMessageResponse{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderMessageResponse) ProtoMessage() {}

func (x *CreateOrderMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderMessageResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderMessageResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderMessageResponse) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

// todo 商品下单(购物车)
type CreateOrderCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=ProductId,proto3" json:"ProductId,omitempty"`
	Pay           int64                  `protobuf:"varint,3,opt,name=Pay,proto3" json:"Pay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderCartRequest) Reset() {
	*x = CreateOrderCartRequest{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderCartRequest) ProtoMessage() {}

func (x *CreateOrderCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderCartRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderCartRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *CreateOrderCartRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderCartRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateOrderCartRequest) GetPay() int64 {
	if x != nil {
		return x.Pay
	}
	return 0
}

type CreateOrderCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=Url,proto3" json:"Url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderCartResponse) Reset() {
	*x = CreateOrderCartResponse{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderCartResponse) ProtoMessage() {}

func (x *CreateOrderCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderCartResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderCartResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *CreateOrderCartResponse) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateOrderCartResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// todo 商品下单(砍价商品)
type CreateOrderBargainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BargainId     int64                  `protobuf:"varint,1,opt,name=BargainId,proto3" json:"BargainId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderBargainRequest) Reset() {
	*x = CreateOrderBargainRequest{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderBargainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderBargainRequest) ProtoMessage() {}

func (x *CreateOrderBargainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderBargainRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderBargainRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *CreateOrderBargainRequest) GetBargainId() int64 {
	if x != nil {
		return x.BargainId
	}
	return 0
}

func (x *CreateOrderBargainRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateOrderBargainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=Url,proto3" json:"Url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderBargainResponse) Reset() {
	*x = CreateOrderBargainResponse{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderBargainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderBargainResponse) ProtoMessage() {}

func (x *CreateOrderBargainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderBargainResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderBargainResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *CreateOrderBargainResponse) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateOrderBargainResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// todo 订单支付(异步)
type OrderPayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	Pay           int64                  `protobuf:"varint,3,opt,name=Pay,proto3" json:"Pay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPayRequest) Reset() {
	*x = OrderPayRequest{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPayRequest) ProtoMessage() {}

func (x *OrderPayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPayRequest.ProtoReflect.Descriptor instead.
func (*OrderPayRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *OrderPayRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderPayRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderPayRequest) GetPay() int64 {
	if x != nil {
		return x.Pay
	}
	return 0
}

type OrderPayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=Url,proto3" json:"Url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPayResponse) Reset() {
	*x = OrderPayResponse{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPayResponse) ProtoMessage() {}

func (x *OrderPayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPayResponse.ProtoReflect.Descriptor instead.
func (*OrderPayResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

func (x *OrderPayResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// todo 支付回调
type OrderPayBakeCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	Status        int64                  `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPayBakeCallRequest) Reset() {
	*x = OrderPayBakeCallRequest{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPayBakeCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPayBakeCallRequest) ProtoMessage() {}

func (x *OrderPayBakeCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPayBakeCallRequest.ProtoReflect.Descriptor instead.
func (*OrderPayBakeCallRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

func (x *OrderPayBakeCallRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderPayBakeCallRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type OrderPayBakeCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPayBakeCallResponse) Reset() {
	*x = OrderPayBakeCallResponse{}
	mi := &file_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPayBakeCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPayBakeCallResponse) ProtoMessage() {}

func (x *OrderPayBakeCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPayBakeCallResponse.ProtoReflect.Descriptor instead.
func (*OrderPayBakeCallResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{11}
}

func (x *OrderPayBakeCallResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// TODO 根据订单号生成二维码
type CreateOrCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	MerId         int64                  `protobuf:"varint,3,opt,name=MerId,proto3" json:"MerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrCodeRequest) Reset() {
	*x = CreateOrCodeRequest{}
	mi := &file_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrCodeRequest) ProtoMessage() {}

func (x *CreateOrCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrCodeRequest.ProtoReflect.Descriptor instead.
func (*CreateOrCodeRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{12}
}

func (x *CreateOrCodeRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateOrCodeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrCodeRequest) GetMerId() int64 {
	if x != nil {
		return x.MerId
	}
	return 0
}

type CreateOrCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       string                 `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrCodeResponse) Reset() {
	*x = CreateOrCodeResponse{}
	mi := &file_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrCodeResponse) ProtoMessage() {}

func (x *CreateOrCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrCodeResponse.ProtoReflect.Descriptor instead.
func (*CreateOrCodeResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{13}
}

func (x *CreateOrCodeResponse) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

// todo 商家统计销售额
type MerchantCountAmountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerId         int64                  `protobuf:"varint,1,opt,name=MerId,proto3" json:"MerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantCountAmountRequest) Reset() {
	*x = MerchantCountAmountRequest{}
	mi := &file_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantCountAmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantCountAmountRequest) ProtoMessage() {}

func (x *MerchantCountAmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantCountAmountRequest.ProtoReflect.Descriptor instead.
func (*MerchantCountAmountRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{14}
}

func (x *MerchantCountAmountRequest) GetMerId() int64 {
	if x != nil {
		return x.MerId
	}
	return 0
}

type MerchantCountAmountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float32                `protobuf:"fixed32,1,opt,name=Amount,proto3" json:"Amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantCountAmountResponse) Reset() {
	*x = MerchantCountAmountResponse{}
	mi := &file_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantCountAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantCountAmountResponse) ProtoMessage() {}

func (x *MerchantCountAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantCountAmountResponse.ProtoReflect.Descriptor instead.
func (*MerchantCountAmountResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{15}
}

func (x *MerchantCountAmountResponse) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// todo:生成订单
type OrderCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"` //todo: 用户Id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreateRequest) Reset() {
	*x = OrderCreateRequest{}
	mi := &file_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreateRequest) ProtoMessage() {}

func (x *OrderCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreateRequest.ProtoReflect.Descriptor instead.
func (*OrderCreateRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{16}
}

func (x *OrderCreateRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type OrderCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       string                 `protobuf:"bytes,1,opt,name=Success,proto3" json:"Success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreateResponse) Reset() {
	*x = OrderCreateResponse{}
	mi := &file_order_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreateResponse) ProtoMessage() {}

func (x *OrderCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreateResponse.ProtoReflect.Descriptor instead.
func (*OrderCreateResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{17}
}

func (x *OrderCreateResponse) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x05order\"n\n" +
	"\x12CreateOrderRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x1c\n" +
	"\tProductId\x18\x02 \x01(\x03R\tProductId\x12\x10\n" +
	"\x03Num\x18\x03 \x01(\x03R\x03Num\x12\x10\n" +
	"\x03Pay\x18\x04 \x01(\x03R\x03Pay\"A\n" +
	"\x13CreateOrderResponse\x12\x18\n" +
	"\aOrderSn\x18\x01 \x01(\tR\aOrderSn\x12\x10\n" +
	"\x03Url\x18\x02 \x01(\tR\x03Url\"\x1b\n" +
	"\x19CreateOrderMessageRequest\"0\n" +
	"\x1aCreateOrderMessageResponse\x12\x12\n" +
	"\x04Ping\x18\x01 \x01(\tR\x04Ping\"`\n" +
	"\x16CreateOrderCartRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x1c\n" +
	"\tProductId\x18\x02 \x01(\x03R\tProductId\x12\x10\n" +
	"\x03Pay\x18\x03 \x01(\x03R\x03Pay\"E\n" +
	"\x17CreateOrderCartResponse\x12\x18\n" +
	"\aOrderId\x18\x01 \x01(\x03R\aOrderId\x12\x10\n" +
	"\x03Url\x18\x02 \x01(\tR\x03Url\"Q\n" +
	"\x19CreateOrderBargainRequest\x12\x1c\n" +
	"\tBargainId\x18\x01 \x01(\x03R\tBargainId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\"H\n" +
	"\x1aCreateOrderBargainResponse\x12\x18\n" +
	"\aOrderId\x18\x01 \x01(\x03R\aOrderId\x12\x10\n" +
	"\x03Url\x18\x02 \x01(\tR\x03Url\"U\n" +
	"\x0fOrderPayRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x18\n" +
	"\aOrderId\x18\x02 \x01(\x03R\aOrderId\x12\x10\n" +
	"\x03Pay\x18\x03 \x01(\x03R\x03Pay\"$\n" +
	"\x10OrderPayResponse\x12\x10\n" +
	"\x03Url\x18\x01 \x01(\tR\x03Url\"K\n" +
	"\x17OrderPayBakeCallRequest\x12\x18\n" +
	"\aOrderId\x18\x01 \x01(\tR\aOrderId\x12\x16\n" +
	"\x06Status\x18\x02 \x01(\x03R\x06Status\"4\n" +
	"\x18OrderPayBakeCallResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\"]\n" +
	"\x13CreateOrCodeRequest\x12\x18\n" +
	"\aOrderId\x18\x01 \x01(\x03R\aOrderId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\x12\x14\n" +
	"\x05MerId\x18\x03 \x01(\x03R\x05MerId\"0\n" +
	"\x14CreateOrCodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\tR\asuccess\"2\n" +
	"\x1aMerchantCountAmountRequest\x12\x14\n" +
	"\x05MerId\x18\x01 \x01(\x03R\x05MerId\"5\n" +
	"\x1bMerchantCountAmountResponse\x12\x16\n" +
	"\x06Amount\x18\x01 \x01(\x02R\x06Amount\",\n" +
	"\x12OrderCreateRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\"/\n" +
	"\x13OrderCreateResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\tR\aSuccess2\xd4\x05\n" +
	"\x05Order\x12D\n" +
	"\vCreateOrder\x12\x19.order.CreateOrderRequest\x1a\x1a.order.CreateOrderResponse\x12Y\n" +
	"\x12CreateOrderMessage\x12 .order.CreateOrderMessageRequest\x1a!.order.CreateOrderMessageResponse\x12P\n" +
	"\x0fCreateOrderCart\x12\x1d.order.CreateOrderCartRequest\x1a\x1e.order.CreateOrderCartResponse\x12;\n" +
	"\bOrderPay\x12\x16.order.OrderPayRequest\x1a\x17.order.OrderPayResponse\x12S\n" +
	"\x10OrderPayBakeCall\x12\x1e.order.OrderPayBakeCallRequest\x1a\x1f.order.OrderPayBakeCallResponse\x12Y\n" +
	"\x12CreateOrderBargain\x12 .order.CreateOrderBargainRequest\x1a!.order.CreateOrderBargainResponse\x12G\n" +
	"\fCreateOrCode\x12\x1a.order.CreateOrCodeRequest\x1a\x1b.order.CreateOrCodeResponse\x12\\\n" +
	"\x13MerchantCountAmount\x12!.order.MerchantCountAmountRequest\x1a\".order.MerchantCountAmountResponse\x12D\n" +
	"\vOrderCreate\x12\x19.order.OrderCreateRequest\x1a\x1a.order.OrderCreateResponseB\tZ\a.;orderb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_order_proto_goTypes = []any{
	(*CreateOrderRequest)(nil),          // 0: order.CreateOrderRequest
	(*CreateOrderResponse)(nil),         // 1: order.CreateOrderResponse
	(*CreateOrderMessageRequest)(nil),   // 2: order.CreateOrderMessageRequest
	(*CreateOrderMessageResponse)(nil),  // 3: order.CreateOrderMessageResponse
	(*CreateOrderCartRequest)(nil),      // 4: order.CreateOrderCartRequest
	(*CreateOrderCartResponse)(nil),     // 5: order.CreateOrderCartResponse
	(*CreateOrderBargainRequest)(nil),   // 6: order.CreateOrderBargainRequest
	(*CreateOrderBargainResponse)(nil),  // 7: order.CreateOrderBargainResponse
	(*OrderPayRequest)(nil),             // 8: order.OrderPayRequest
	(*OrderPayResponse)(nil),            // 9: order.OrderPayResponse
	(*OrderPayBakeCallRequest)(nil),     // 10: order.OrderPayBakeCallRequest
	(*OrderPayBakeCallResponse)(nil),    // 11: order.OrderPayBakeCallResponse
	(*CreateOrCodeRequest)(nil),         // 12: order.CreateOrCodeRequest
	(*CreateOrCodeResponse)(nil),        // 13: order.CreateOrCodeResponse
	(*MerchantCountAmountRequest)(nil),  // 14: order.MerchantCountAmountRequest
	(*MerchantCountAmountResponse)(nil), // 15: order.MerchantCountAmountResponse
	(*OrderCreateRequest)(nil),          // 16: order.OrderCreateRequest
	(*OrderCreateResponse)(nil),         // 17: order.OrderCreateResponse
}
var file_order_proto_depIdxs = []int32{
	0,  // 0: order.Order.CreateOrder:input_type -> order.CreateOrderRequest
	2,  // 1: order.Order.CreateOrderMessage:input_type -> order.CreateOrderMessageRequest
	4,  // 2: order.Order.CreateOrderCart:input_type -> order.CreateOrderCartRequest
	8,  // 3: order.Order.OrderPay:input_type -> order.OrderPayRequest
	10, // 4: order.Order.OrderPayBakeCall:input_type -> order.OrderPayBakeCallRequest
	6,  // 5: order.Order.CreateOrderBargain:input_type -> order.CreateOrderBargainRequest
	12, // 6: order.Order.CreateOrCode:input_type -> order.CreateOrCodeRequest
	14, // 7: order.Order.MerchantCountAmount:input_type -> order.MerchantCountAmountRequest
	16, // 8: order.Order.OrderCreate:input_type -> order.OrderCreateRequest
	1,  // 9: order.Order.CreateOrder:output_type -> order.CreateOrderResponse
	3,  // 10: order.Order.CreateOrderMessage:output_type -> order.CreateOrderMessageResponse
	5,  // 11: order.Order.CreateOrderCart:output_type -> order.CreateOrderCartResponse
	9,  // 12: order.Order.OrderPay:output_type -> order.OrderPayResponse
	11, // 13: order.Order.OrderPayBakeCall:output_type -> order.OrderPayBakeCallResponse
	7,  // 14: order.Order.CreateOrderBargain:output_type -> order.CreateOrderBargainResponse
	13, // 15: order.Order.CreateOrCode:output_type -> order.CreateOrCodeResponse
	15, // 16: order.Order.MerchantCountAmount:output_type -> order.MerchantCountAmountResponse
	17, // 17: order.Order.OrderCreate:output_type -> order.OrderCreateResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
