// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: collection.proto

package collection

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// todo:数据收集
type DataCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataCollectionRequest) Reset() {
	*x = DataCollectionRequest{}
	mi := &file_collection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataCollectionRequest) ProtoMessage() {}

func (x *DataCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataCollectionRequest.ProtoReflect.Descriptor instead.
func (*DataCollectionRequest) Descriptor() ([]byte, []int) {
	return file_collection_proto_rawDescGZIP(), []int{0}
}

type DataCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataCollectionResponse) Reset() {
	*x = DataCollectionResponse{}
	mi := &file_collection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataCollectionResponse) ProtoMessage() {}

func (x *DataCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataCollectionResponse.ProtoReflect.Descriptor instead.
func (*DataCollectionResponse) Descriptor() ([]byte, []int) {
	return file_collection_proto_rawDescGZIP(), []int{1}
}

func (x *DataCollectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// todo:信息入库
type InformationStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Tid           int64                  `protobuf:"varint,2,opt,name=Tid,proto3" json:"Tid,omitempty"`
	Heartbeat     string                 `protobuf:"bytes,3,opt,name=Heartbeat,proto3" json:"Heartbeat,omitempty"` //心率数据
	Database      string                 `protobuf:"bytes,4,opt,name=Database,proto3" json:"Database,omitempty"`
	Table         string                 `protobuf:"bytes,5,opt,name=Table,proto3" json:"Table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InformationStoreRequest) Reset() {
	*x = InformationStoreRequest{}
	mi := &file_collection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InformationStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformationStoreRequest) ProtoMessage() {}

func (x *InformationStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformationStoreRequest.ProtoReflect.Descriptor instead.
func (*InformationStoreRequest) Descriptor() ([]byte, []int) {
	return file_collection_proto_rawDescGZIP(), []int{2}
}

func (x *InformationStoreRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *InformationStoreRequest) GetTid() int64 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *InformationStoreRequest) GetHeartbeat() string {
	if x != nil {
		return x.Heartbeat
	}
	return ""
}

func (x *InformationStoreRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *InformationStoreRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

type InformationStoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InformationStoreResponse) Reset() {
	*x = InformationStoreResponse{}
	mi := &file_collection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InformationStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformationStoreResponse) ProtoMessage() {}

func (x *InformationStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformationStoreResponse.ProtoReflect.Descriptor instead.
func (*InformationStoreResponse) Descriptor() ([]byte, []int) {
	return file_collection_proto_rawDescGZIP(), []int{3}
}

func (x *InformationStoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

//todo:redis消息缓存
type MessageCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Tid           int64                  `protobuf:"varint,2,opt,name=Tid,proto3" json:"Tid,omitempty"`
	Heartbeat     string                 `protobuf:"bytes,3,opt,name=Heartbeat,proto3" json:"Heartbeat,omitempty"` //心率数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageCacheRequest) Reset() {
	*x = MessageCacheRequest{}
	mi := &file_collection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageCacheRequest) ProtoMessage() {}

func (x *MessageCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageCacheRequest.ProtoReflect.Descriptor instead.
func (*MessageCacheRequest) Descriptor() ([]byte, []int) {
	return file_collection_proto_rawDescGZIP(), []int{4}
}

func (x *MessageCacheRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *MessageCacheRequest) GetTid() int64 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *MessageCacheRequest) GetHeartbeat() string {
	if x != nil {
		return x.Heartbeat
	}
	return ""
}

type MessageCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageCacheResponse) Reset() {
	*x = MessageCacheResponse{}
	mi := &file_collection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageCacheResponse) ProtoMessage() {}

func (x *MessageCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageCacheResponse.ProtoReflect.Descriptor instead.
func (*MessageCacheResponse) Descriptor() ([]byte, []int) {
	return file_collection_proto_rawDescGZIP(), []int{5}
}

func (x *MessageCacheResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

//todo:redis缓存消息查看
type GetMessageCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageCacheRequest) Reset() {
	*x = GetMessageCacheRequest{}
	mi := &file_collection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageCacheRequest) ProtoMessage() {}

func (x *GetMessageCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageCacheRequest.ProtoReflect.Descriptor instead.
func (*GetMessageCacheRequest) Descriptor() ([]byte, []int) {
	return file_collection_proto_rawDescGZIP(), []int{6}
}

func (x *GetMessageCacheRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetMessageCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	List          []*GetMessageCache     `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageCacheResponse) Reset() {
	*x = GetMessageCacheResponse{}
	mi := &file_collection_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageCacheResponse) ProtoMessage() {}

func (x *GetMessageCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collection_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageCacheResponse.ProtoReflect.Descriptor instead.
func (*GetMessageCacheResponse) Descriptor() ([]byte, []int) {
	return file_collection_proto_rawDescGZIP(), []int{7}
}

func (x *GetMessageCacheResponse) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetMessageCacheResponse) GetList() []*GetMessageCache {
	if x != nil {
		return x.List
	}
	return nil
}

type GetMessageCache struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Heartbeat     string                 `protobuf:"bytes,1,opt,name=Heartbeat,proto3" json:"Heartbeat,omitempty"` //心率数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageCache) Reset() {
	*x = GetMessageCache{}
	mi := &file_collection_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageCache) ProtoMessage() {}

func (x *GetMessageCache) ProtoReflect() protoreflect.Message {
	mi := &file_collection_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageCache.ProtoReflect.Descriptor instead.
func (*GetMessageCache) Descriptor() ([]byte, []int) {
	return file_collection_proto_rawDescGZIP(), []int{8}
}

func (x *GetMessageCache) GetHeartbeat() string {
	if x != nil {
		return x.Heartbeat
	}
	return ""
}

// todo:数据清洗
type DataCleaningRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataCleaningRequest) Reset() {
	*x = DataCleaningRequest{}
	mi := &file_collection_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataCleaningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataCleaningRequest) ProtoMessage() {}

func (x *DataCleaningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collection_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataCleaningRequest.ProtoReflect.Descriptor instead.
func (*DataCleaningRequest) Descriptor() ([]byte, []int) {
	return file_collection_proto_rawDescGZIP(), []int{9}
}

type DataCleaningResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataCleaningResponse) Reset() {
	*x = DataCleaningResponse{}
	mi := &file_collection_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataCleaningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataCleaningResponse) ProtoMessage() {}

func (x *DataCleaningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collection_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataCleaningResponse.ProtoReflect.Descriptor instead.
func (*DataCleaningResponse) Descriptor() ([]byte, []int) {
	return file_collection_proto_rawDescGZIP(), []int{10}
}

func (x *DataCleaningResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// todo:数据分析
type DataAnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataAnalysisRequest) Reset() {
	*x = DataAnalysisRequest{}
	mi := &file_collection_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataAnalysisRequest) ProtoMessage() {}

func (x *DataAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collection_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataAnalysisRequest.ProtoReflect.Descriptor instead.
func (*DataAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_collection_proto_rawDescGZIP(), []int{11}
}

type DataAnalysisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Rete          int64                  `protobuf:"varint,2,opt,name=Rete,proto3" json:"Rete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataAnalysisResponse) Reset() {
	*x = DataAnalysisResponse{}
	mi := &file_collection_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataAnalysisResponse) ProtoMessage() {}

func (x *DataAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collection_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataAnalysisResponse.ProtoReflect.Descriptor instead.
func (*DataAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_collection_proto_rawDescGZIP(), []int{12}
}

func (x *DataAnalysisResponse) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *DataAnalysisResponse) GetRete() int64 {
	if x != nil {
		return x.Rete
	}
	return 0
}

// todo:状态修改
type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Rete          int64                  `protobuf:"varint,2,opt,name=Rete,proto3" json:"Rete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_collection_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collection_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_collection_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateStatusRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UpdateStatusRequest) GetRete() int64 {
	if x != nil {
		return x.Rete
	}
	return 0
}

type UpdateStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusResponse) Reset() {
	*x = UpdateStatusResponse{}
	mi := &file_collection_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusResponse) ProtoMessage() {}

func (x *UpdateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collection_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateStatusResponse) Descriptor() ([]byte, []int) {
	return file_collection_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_collection_proto protoreflect.FileDescriptor

const file_collection_proto_rawDesc = "" +
	"\n" +
	"\x10collection.proto\x12\n" +
	"collection\"\x17\n" +
	"\x15DataCollectionRequest\"2\n" +
	"\x16DataCollectionResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\"\x8d\x01\n" +
	"\x17InformationStoreRequest\x12\x10\n" +
	"\x03Uid\x18\x01 \x01(\x03R\x03Uid\x12\x10\n" +
	"\x03Tid\x18\x02 \x01(\x03R\x03Tid\x12\x1c\n" +
	"\tHeartbeat\x18\x03 \x01(\tR\tHeartbeat\x12\x1a\n" +
	"\bDatabase\x18\x04 \x01(\tR\bDatabase\x12\x14\n" +
	"\x05Table\x18\x05 \x01(\tR\x05Table\"4\n" +
	"\x18InformationStoreResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\"W\n" +
	"\x13MessageCacheRequest\x12\x10\n" +
	"\x03Uid\x18\x01 \x01(\x03R\x03Uid\x12\x10\n" +
	"\x03Tid\x18\x02 \x01(\x03R\x03Tid\x12\x1c\n" +
	"\tHeartbeat\x18\x03 \x01(\tR\tHeartbeat\"0\n" +
	"\x14MessageCacheResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\"*\n" +
	"\x16GetMessageCacheRequest\x12\x10\n" +
	"\x03Uid\x18\x01 \x01(\x03R\x03Uid\"\\\n" +
	"\x17GetMessageCacheResponse\x12\x10\n" +
	"\x03Uid\x18\x01 \x01(\x03R\x03Uid\x12/\n" +
	"\x04list\x18\x02 \x03(\v2\x1b.collection.GetMessageCacheR\x04list\"/\n" +
	"\x0fGetMessageCache\x12\x1c\n" +
	"\tHeartbeat\x18\x01 \x01(\tR\tHeartbeat\"\x15\n" +
	"\x13DataCleaningRequest\"0\n" +
	"\x14DataCleaningResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\"\x15\n" +
	"\x13DataAnalysisRequest\"<\n" +
	"\x14DataAnalysisResponse\x12\x10\n" +
	"\x03Uid\x18\x01 \x01(\x03R\x03Uid\x12\x12\n" +
	"\x04Rete\x18\x02 \x01(\x03R\x04Rete\";\n" +
	"\x13UpdateStatusRequest\x12\x10\n" +
	"\x03Uid\x18\x01 \x01(\x03R\x03Uid\x12\x12\n" +
	"\x04Rete\x18\x02 \x01(\x03R\x04Rete\"0\n" +
	"\x14UpdateStatusResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess2\xec\x04\n" +
	"\n" +
	"Collection\x12W\n" +
	"\x0eDataCollection\x12!.collection.DataCollectionRequest\x1a\".collection.DataCollectionResponse\x12]\n" +
	"\x10InformationStore\x12#.collection.InformationStoreRequest\x1a$.collection.InformationStoreResponse\x12Q\n" +
	"\fMessageCache\x12\x1f.collection.MessageCacheRequest\x1a .collection.MessageCacheResponse\x12Z\n" +
	"\x0fGetMessageCache\x12\".collection.GetMessageCacheRequest\x1a#.collection.GetMessageCacheResponse\x12Q\n" +
	"\fDataCleaning\x12\x1f.collection.DataCleaningRequest\x1a .collection.DataCleaningResponse\x12Q\n" +
	"\fDataAnalysis\x12\x1f.collection.DataAnalysisRequest\x1a .collection.DataAnalysisResponse\x12Q\n" +
	"\fUpdateStatus\x12\x1f.collection.UpdateStatusRequest\x1a .collection.UpdateStatusResponseB\x0eZ\f./collectionb\x06proto3"

var (
	file_collection_proto_rawDescOnce sync.Once
	file_collection_proto_rawDescData []byte
)

func file_collection_proto_rawDescGZIP() []byte {
	file_collection_proto_rawDescOnce.Do(func() {
		file_collection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_collection_proto_rawDesc), len(file_collection_proto_rawDesc)))
	})
	return file_collection_proto_rawDescData
}

var file_collection_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_collection_proto_goTypes = []any{
	(*DataCollectionRequest)(nil),    // 0: collection.DataCollectionRequest
	(*DataCollectionResponse)(nil),   // 1: collection.DataCollectionResponse
	(*InformationStoreRequest)(nil),  // 2: collection.InformationStoreRequest
	(*InformationStoreResponse)(nil), // 3: collection.InformationStoreResponse
	(*MessageCacheRequest)(nil),      // 4: collection.MessageCacheRequest
	(*MessageCacheResponse)(nil),     // 5: collection.MessageCacheResponse
	(*GetMessageCacheRequest)(nil),   // 6: collection.GetMessageCacheRequest
	(*GetMessageCacheResponse)(nil),  // 7: collection.GetMessageCacheResponse
	(*GetMessageCache)(nil),          // 8: collection.GetMessageCache
	(*DataCleaningRequest)(nil),      // 9: collection.DataCleaningRequest
	(*DataCleaningResponse)(nil),     // 10: collection.DataCleaningResponse
	(*DataAnalysisRequest)(nil),      // 11: collection.DataAnalysisRequest
	(*DataAnalysisResponse)(nil),     // 12: collection.DataAnalysisResponse
	(*UpdateStatusRequest)(nil),      // 13: collection.UpdateStatusRequest
	(*UpdateStatusResponse)(nil),     // 14: collection.UpdateStatusResponse
}
var file_collection_proto_depIdxs = []int32{
	8,  // 0: collection.GetMessageCacheResponse.list:type_name -> collection.GetMessageCache
	0,  // 1: collection.Collection.DataCollection:input_type -> collection.DataCollectionRequest
	2,  // 2: collection.Collection.InformationStore:input_type -> collection.InformationStoreRequest
	4,  // 3: collection.Collection.MessageCache:input_type -> collection.MessageCacheRequest
	6,  // 4: collection.Collection.GetMessageCache:input_type -> collection.GetMessageCacheRequest
	9,  // 5: collection.Collection.DataCleaning:input_type -> collection.DataCleaningRequest
	11, // 6: collection.Collection.DataAnalysis:input_type -> collection.DataAnalysisRequest
	13, // 7: collection.Collection.UpdateStatus:input_type -> collection.UpdateStatusRequest
	1,  // 8: collection.Collection.DataCollection:output_type -> collection.DataCollectionResponse
	3,  // 9: collection.Collection.InformationStore:output_type -> collection.InformationStoreResponse
	5,  // 10: collection.Collection.MessageCache:output_type -> collection.MessageCacheResponse
	7,  // 11: collection.Collection.GetMessageCache:output_type -> collection.GetMessageCacheResponse
	10, // 12: collection.Collection.DataCleaning:output_type -> collection.DataCleaningResponse
	12, // 13: collection.Collection.DataAnalysis:output_type -> collection.DataAnalysisResponse
	14, // 14: collection.Collection.UpdateStatus:output_type -> collection.UpdateStatusResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_collection_proto_init() }
func file_collection_proto_init() {
	if File_collection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_collection_proto_rawDesc), len(file_collection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collection_proto_goTypes,
		DependencyIndexes: file_collection_proto_depIdxs,
		MessageInfos:      file_collection_proto_msgTypes,
	}.Build()
	File_collection_proto = out.File
	file_collection_proto_goTypes = nil
	file_collection_proto_depIdxs = nil
}
